// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo2_VL_yYoFUKHqEezr57c_MUwZ9pzJWQ',
    appId: '1:1062931751295:web:6470233b2e1260af747a4a',
    messagingSenderId: '1062931751295',
    projectId: 'medguide-5898e',
    authDomain: 'medguide-5898e.firebaseapp.com',
    storageBucket: 'medguide-5898e.firebasestorage.app',
    measurementId: 'G-RJ3Q2VFE7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwkPWH8o3l0dOK0cbN2xfUCCyU3PjWrnA',
    appId: '1:1062931751295:android:59d815507078b79c747a4a',
    messagingSenderId: '1062931751295',
    projectId: 'medguide-5898e',
    storageBucket: 'medguide-5898e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo2_VL_yYoFUKHqEezr57c_MUwZ9pzJWQ',
    appId: '1:1062931751295:web:73e7587a76c176d9747a4a',
    messagingSenderId: '1062931751295',
    projectId: 'medguide-5898e',
    authDomain: 'medguide-5898e.firebaseapp.com',
    storageBucket: 'medguide-5898e.firebasestorage.app',
    measurementId: 'G-S3RHPT0M3E',
  );
}
